config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get 'our_work', to: 'pages#our_work'
  get 'success_stories', to: 'pages#success_stories'
  get 'services', to: 'pages#services'
  get 'blog', to: 'pages#blog'
  get 'contact', to: 'pages#contact'
  get 'prices', to: 'pages#prices'
  get 'events', to: 'pages#events'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
  
    def our_work
    end
  
    def success_stories
    end
  
    def services
    end
  
    def blog
    end
  
    def contact
    end
  
    def prices
    end
  
    def events
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elbornlabv3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/blog.html.erb
<!DOCTYPE>
<html>
<head>
<title></title>
</head>
<body>
<p></p>
</body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script> 

          <!-- Google result text-->
        <title>El Born Lab - Contact Us</title>
        <!-- Google result description-->
        <meta name="description" content="Let's have a chat. We'd love to hear from you.">
        <!-- og Is Open Graph tagging used by Facebook and Twitter has a siilar one.-->
        <!--  Essential META Tags -->
        <meta property="og:title" content="El Born Lab - Contact Us">
        <meta property="og:image" content="https://elbornlab.com/contact_us.jpg">
        <meta property="og:description" content="We'd love to hear from you.">
        <meta property="og:url" content="https://elbornlab.com/contact">
        <meta name="twitter:card" content="summary_large_image">
        <!--  Non-Essential, But Recommended -->
        <meta property="og:site_name" content="El Born Lab - Contact">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
    <body>
    <%= render 'shared/navbar-simple' %> 
    <div class="container">
    
        <div class="card border-0 mt-5">
            <div class="text-greeting">
            <p>Let's have a chat</p>
            </div>
            <div class="text-value">
            <p>Contact Us</p>
            </div>
            <div class="text-ouremail">
            <a href="mailto:someone@yoursite.com" class="text-ouremail">hola@elbornlab.com</a> 
            </div>
            <div class="text-ournumbers">
            <p>+34 671 299 969</p>
            <p class="text-visitus"><a class="text-visitus" href="https://goo.gl/maps/zUrVgaprQp5EbLpQ7" target="_blank" rel="noopener noreferrer">Visit us in Barcelona</a></p> 
            </div>
        </div>
    </div>
<div class="bg_black">
    <div class="container mt-4 pb-4">
        <form action="https://formspree.io/f/mwkaorna" method="POST">
        <p class="text-formintro_new pt-4"> We'd love to hear from you. </p>
        <p class="text-formyourdetails"> Your details </p>
        <div class="row align-items-center row-cols-1 row-cols-md-2 g-4">
            <div class="col">  
                <p class="text-formyourinfo"> Your firstname </p>       
                <input 
                type="text" 
                name="firstname"
                style="background-color:white; 
                vertical-align:9px;color: #4F4F4F"> 
            </div>
            <div class="col">
                <p class="text-formyourinfo"> Your surname </p>
                    <input 
                    type="text" 
                    name="lastname"
                    style="background-color:white; 
                vertical-align:9px;color: #4F4F4F">
            </div>
            <div class="col">
            <p class="text-formyourinfo"> Contact number </p>
            <input 
            type="text" 
            name="telephone"
            style="background-color:white; 
                vertical-align:9px;color: #4F4F4F">
            </div>
            <div class="col">
            <p class="text-formyourinfo"> Country </p>
                <input 
                type="text" 
                name="Country"
                style="background-color:white; 
                vertical-align:9px;color: #4F4F4F"> 
            </div>
            <div class="col">
            <p class="text-formyourinfo"> Your company </p>
                <input 
                type="text" 
                name="Company"
                style="background-color:white; 
                vertical-align:9px;color:black"> 
            </div>
            <div class="col">
            <p class="text-formyourinfo"> Contact email </p>
            <input 
            type="email" 
            name="_replyto"
            style="background-color:white; 
            vertical-align:9px;color:black">
            </div> 
        </div>
        
        <p class="text-formhowcanhelp"> How can we help? </p>
        <p class="text-formyourinfo"> Tell us about your project </p>
        <textarea style="width:65%" name="message"></textarea>
        <div class="row row-cols-1 row-cols-md-1 g-4">
            <div class="col">
            <!-- 
            <button type="submit" class="btn btn-flat"> -->
            <button type="submit" class="btn-treehouse">
            <i class="far fa-paper-plane"></i> Send Info
            </button>
        </form>
            </div>
        </div>
        <p class="text-privpolicy"> We'll only use your information to help us handle your enquiry, as explained in our Privacy Policy. </p>
        <div class="row">
            <div class="col-6">
            <p class="text-formhowcanhelp">Say hello</p>
            <p class="text-ournumber_small">+34 6712 99969</p>
            <p class="text-ouremail_small">hola@elbornlab.com</p>
            <p class="text-ouremail_small">LinkedIn</p>
            <p></p>
            </div>
            <div class="col-6">
            <p class="text-formhowcanhelp">Take a look</p>
            <p class="text-ournumber_small">Our work</p>
            <p class="text-ouremail_small">Success stories</p>
            <p class="text-ouremail_small">Services</p>
            <p class="text-ouremail_small">Blog</p>
            <p class="text-ouremail_small">Contact us</p>
            <p></p>
            </div>
        </div>
        <p class="text-formyourinfo">Copyright © 2021</p>
        <p class="text-formyourinfo">El Born Lab</p>
        <p class="text-formyourinfo">Plaça de Sant Pere 13</p>
        <p class="text-formyourinfo">08003 Barcelona</p>
        <p class="text-formyourinfo"><a class="text-addrslink" href="https://goo.gl/maps/zUrVgaprQp5EbLpQ7" target="_blank" rel="noopener noreferrer">View on map</a></p>
        
    </div>
</div>

     
  </body>
</html>

app/views/pages/events.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script>
        <!-- Google result text-->
    <title>El Born Lab - Events: Things We Teach</title>
    <!-- Google result description-->
    <meta name="description" content="Our workshops and courses are for beginners or those who want to improve their existing developer skills. In-addition, our cyber security courses provide a deep understanding of techniques hackers use to break apps.">

<!--  Essential META Tags -->
    <meta property="og:title" content="El Born Lab">
    <meta property="og:description" content="Our workshops and courses are for beginners or those who want to improve their existing developer skills.">
    <meta property="og:image" content="https://elbornlab.com/prototype.jpg">
    <meta property="og:url" content="https://elbornlab.com/events">
    <meta name="twitter:card" content="summary_large_image">
    <!--  Non-Essential, But Recommended -->
    <meta property="og:site_name" content="El Born Lab - Events">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
  <body>
    <%= render 'shared/navbar-simple' %>
    <%= render 'shared/events_section' %>  


  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
          <!-- Google result text-->
        <title>El Born Lab - We Build Digital Products</title>
        <%= favicon_link_tag 'favicon.ico' %>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script>
        <!-- Google result description-->
        <meta name="description" content="We build digital products for brands and startups. Delivering beautifully crafted web and mobile applications, providing SEO capability and expert cyber security services.">
        <!-- og Is Open Graph tagging used by Facebook and Twitter has a siilar one.-->
        <!--  Essential META Tags -->
        <meta property="og:title" content="El Born Lab">
        <meta property="og:image" content="https://elbornlab.com/appdev.jpg">
        <meta property="og:description" content="We build digital products for brands and startups. Delivering beautifully crafted web and mobile applications, providing SEO capability and expert cyber security services.">
        <meta property="og:url" content="https://elbornlab.com">
        <meta name="twitter:card" content="summary_large_image">
        <!--  Non-Essential, But Recommended -->
        <meta property="og:site_name" content="El Born Lab">

        <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
  <body>
     <%= render 'shared/navbar-simple' %>
      <div class="container">
          <div class="text-greeting mt-5">
              <p>Hola</p>
          </div>
          <div class="text-value">
              <p>We build digital products for brands and startups. Delivering beautifully crafted web and mobile applications, providing SEO capability and expert cybersecurity services.</p>
          </div>
          <div class="text-greeting2">
              <p>Have a look at <a href="#" class="text-landing-link">what we do</a>, our past <a href="#" class="text-landing-link">success stories</a> and feel free to <a href="#" class="text-landing-link">get in touch</a>.</p>
          </div>
          <div class="row">
              <div class="col-3 mx-auto">
                  <div class="card border-0 align-items-center mb-4">
                      <div class="embed-responsive embed-responsive-16by9 bg-transparent border-0">
                          <iframe class="embed-responsive-item border-0 w-100" src="https://res.cloudinary.com/dspkvxtxa/video/upload/v1625694684/msj438cwmsqntwvunfx8.mp4" allowfullscreen autoplay></iframe>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <%= render 'shared/ourwork_section' %> 
      <%= render 'shared/services_section' %>

  </body>
</html>

app/views/pages/our_work.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script>
    <title>El Born Lab - Our Work Building Digital Products</title>    
    <!-- Google result description-->
    <meta name="description" content="We combine our application development and deep tech skills with a thorough understanding of our clients’ business needs to deliver projects with results and value.">
    <!--  Essential META Tags -->
    <meta property="og:title" content="El Born Lab - Our Work Building Digital Products">
    <meta property="og:description" content="We bring together our application development and deep tech skills with a thorough understanding of our clients’ business needs to deliver projects with results and value.">
    <meta property="og:image" content="https://elbornlab.com/our_work.jpg">
    <meta property="og:url" content="https://elbornlab.com/our_work">
    <meta name="twitter:card" content="summary_large_image">
    <!--  Non-Essential, But Recommended -->
    <meta property="og:site_name" content="El Born Lab - Our Work">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
  <body>
  
    <%= render 'shared/navbar-simple' %> 
    <%= render 'shared/ourwork_section' %> 

    <%= render 'shared/contact_section.html.erb' %>
    </body>
</html>

app/views/pages/prices.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script>
        <!-- Google result text-->
    <title>El Born Lab - Prices for Digital Products</title>
    <!-- Google result description-->
    <meta name="description" content="Costs for Mobile Apps, from MVP to more sophisticated digital products.">

<!--  Essential META Tags -->
    <meta property="og:title" content="El Born Lab">
    <meta property="og:description" content="We build digital products for brands and startups. These are prices for mobile apps from MVP to more complex feautures.">
    <meta property="og:image" content="https://elbornlab.com/design.jpg">
    <meta property="og:url" content="https://elbornlab.com/prices">
    <meta name="twitter:card" content="summary_large_image">
    <!--  Non-Essential, But Recommended -->
    <meta property="og:site_name" content="El Born Lab - Prices">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
  <body>
    <%= render 'shared/navbar-simple' %>  
    <div class="container">
   
    <div class="card border-0 mt-5">
        <div class="text-greeting">
        <p>What are our rates for Mobile Apps</p>
        </div>
        <div class="text-value">
        <p>Prices</p>
        </div>
        <div class="text-ourwork">
        <p>It's always somewhat tricky to determine the price of a project so we've listed below some of our rates for Mobile Apps. For other services we offer such as Web Design, SEO and Cyber Security please get intouch. If you wish a dedicated team for your project we can work for you directly or put you intouch with oour partner networks.</p>
        </div>
    </div>    
    <div class="row align-items-center">
        <div class="card-deck mt-5">
            <div class="card text-center mb-4 mx-4 border-0">
                <div class="card-header text-card-prices border-0">
                Around 1 month
                </div>
                <div class="card-body">
                <h5 class="card-title">MVP</h5>
                <p class="card-text text-card-prices">The simplest version of any app which validates the product idea and can be demonstrated to potential customers. Typically 1 to 3 developers and design experts. </p>
                <!--  
                <%= link_to "Book a Consultation", contact_path, class: "btn btn-success" %> -->
                </div>
                <div class="card-footer text-muted text-card-price border-0">
                From 15 000 €
                </div>
            </div>
            <div class="card text-center mb-4 mx-4 border-0">
                <div class="card-header  text-card-prices border-0">
                Around 1-2 month
                </div>
                <div class="card-body">
                <h5 class="card-title">Basic</h5>
                <p class="card-text text-card-prices">
                An app in production environment with high availability. For example QR code scanner or inventoy management. Typically 2 developers, designer and QA. 
                </p>
                </div>
                <div class="card-footer text-muted text-card-price border-0">
                20 000 to 45 000 €
                </div>
            </div>
        </div>  
    </div>        
        <div class="row align-items-center"> 
            <div class="card-deck">        
                <div class="card text-center mb-4 mx-4 border-0">
                    <div class="card-header text-card-prices border-0">
                    Around 3-6 months
                    </div>
                    <div class="card-body">
                    <h5 class="card-title">Medium</h5>
                    <p class="card-text text-card-prices">
                    A more sophiscicated app for example a payment app for cashless or a symptoms tracking app. Typically 4 developers, designer, QA and a security engineer.
                    </p>

                    </div>
                    <div class="card-footer text-muted text-card-price border-0">
                    45 000 to 75 000 €
                    </div>
                </div>
                <div class="card text-center mb-4 mx-4 border-0">
                    <div class="card-header text-card-prices border-0">
                    6 months +
                    </div>
                    <div class="card-body">
                    <h5 class="card-title">Complex</h5>
                    <p class="card-text text-card-prices">
                    This maybe a app with banking features, food delivery or an e-wallet app . Typically 4 developers, designer, QA, security engineer and DevOps.
                    </p>
                    </div>
                    <div class="card-footer text-muted text-card-price border-0">
                    75 000 to 130 000 €
                    </div>
                </div>
            </div>
        </div>
        <h3 class="text-ourwork text-justify font-weight-bold my-4 mx-2 ">What is included in the prices of an MVP and apps?</h3>
        <div class="row align-items-center"> 
            <div class="card-deck">
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="uxdesign.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">UX/UI Design</h5>
                    <p class="card-text text-card-price">The graphical layout of the design is built to ensure it is attractive and matches the personality of the app and is seamless. Wireframes are used for rendering initial interface interactions.</p>
                    </div> 
                </div>
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="ios_android.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">Android/iOS Development</h5>
                    <p class="card-text text-card-price">Development of apps on the most popular platforms: Android and iOS. Android is the most popular globally, yet iOS has a higher market share in North America. We development seamless apps on both.</p>
                    </div> 
                </div>
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="training.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">Client training</h5>
                    <p class="card-text text-card-price">We provide documentation and source code upon completion. This is supplemented with training sessions so further changes to the app can be planned and executed to sypport business requirements.</p>
                    </div> 
                </div>
            </div>   
        </div>
        <div class="row align-items-center"> 
            <div class="card-deck">
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="prototype.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">MVP Analysis & Launch</h5>
                    <p class="card-text text-card-price">We review and assist in continously reviewing the strategy for MVP development and ensure the launch of the app successfully meets the anticpated first customer segment.</p>
                    </div> 
                </div>
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="techresearch.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">Technical research</h5>
                    <p class="card-text text-card-price">The technical stack and components design required for the functional and non functional requirements are reviewed and available options researched.</p>
                    </div> 
                </div>
                <div class="card mb-4 mx-4 border-0">
                    <img class="card-img-top" src="delivery.png" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title text-card-price">Delivery requirements</h5>
                    <p class="card-text text-card-price">The criteria for success are met for all the customer requirements and QA testing completed.</p>
                    </div> 
                </div>
            </div>   
        </div>

     </div>  
    <%= render 'shared/contact_section.html.erb' %>
    </body>
</html>

app/views/pages/services.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ME88LD4GDV"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-ME88LD4GDV');
        </script>
        <!-- Google result text-->
    <title>El Born Lab - Digital Services We Provide</title>
    <!-- Google result description-->
    <meta name="description" content="Web and mobile application devlopment, cybersecurity and online brand development.">

<!--  Essential META Tags -->
    <meta property="og:title" content="El Born Lab">
    <meta property="og:description" content="We build digital products for brands and startups. Our core services include Web and mobile application development, cybersecurity and online brand development.">
    <meta property="og:image" content="https://elbornlab.com/products.jpg">
    <meta property="og:url" content="https://elbornlab.com/services">
    <meta name="twitter:card" content="summary_large_image">
    <!--  Non-Essential, But Recommended -->
    <meta property="og:site_name" content="El Born Lab - Services">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    </head>
  <body>
    <%= render 'shared/navbar-simple' %>
    <%= render 'shared/services_section' %>  
    
<%= render 'shared/contact_section.html.erb' %>
  </body>
</html>

app/views/pages/success_stories.html.erb
<!DOCTYPE>
<html>
<head>
<title>Under Construction</title>
</head>
<body>
<p>This page is under construction. Please come back soon!</p>

<a href="testrun.pdf">link text</a>


</body>
</html>

app/views/shared/_banner-image.html.erb
   <%= image_tag 'HClogo.png', class: "img-fluid" %> 

app/views/shared/_navbar-simple.html.erb
<div class="container">

<% if user_signed_in?  %>
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo_full.png", height: 50 %> 
    <% end %>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
        <!-- Login link (when logged out) -->
        <!-- 
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        -->
      <!-- Once auth fixed then delete all the stuff below -->
      <!-- Links when logged in -->
        <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to "Logout", destroy_user_session_path,:method => 'delete', class: "navbar-wagon-item navbar-erikablog-link" %>
        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <!--<%= image_tag "https://images.unsplash.com/photo-1543458104-7d567484d770?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=55e879ad1f3b096771251f579aaa3b1f&auto=format&fit=crop&w=675&q=80", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>-->
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>

      
    </div>
<% else %>

    <div class="navbar-lab">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo_full_white.png", height: 50 %>
    <% end %>

    <!-- Right Navigation -->
    <!-- Hide on sm and xs screens -->
    <div class="navbar-wagon-right d-none d-sm-block d-sm-none d-md-block">
        <!-- Hide on sm and xs screens -->
        <!-- Login link (when logged out) -->
        <!-- 
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        -->
      <!-- Once auth fixed then delete all the stuff below -->
      <!-- Links when logged in -->
        <%= link_to "Our work", our_work_path, class: "navbar-wagon-item navbar-lab-link" %>
        <!-- <%= link_to "Success stories", success_stories_path, class: "navbar-wagon-item navbar-lab-link" %>-->
        <%= link_to "Services", services_path, class: "navbar-wagon-item navbar-lab-link" %>
        <%= link_to "Prices", prices_path, class: "navbar-wagon-item navbar-lab-link" %>
        <%= link_to "Events", events_path, class: "navbar-wagon-item navbar-lab-link" %>
        <a class="navbar-wagon-item navbar-lab-link" href="https://blog.elbornlab.com">Blog</a>
        <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-lab-link" %>
        <!-- Avatar with dropdown menu Not Used Here -->
        <!-- but could be super useful by Haseeb 23 May 2021 -->
        <div class="navbar-wagon-item">
            <div class="dropdown">
            <!--<%= image_tag "https://images.unsplash.com/photo-1543458104-7d567484d770?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=55e879ad1f3b096771251f579aaa3b1f&auto=format&fit=crop&w=675&q=80", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>-->
            <!--<ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>-->
            </div>
        </div> 
    </div>
<% end %>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-block d-sm-none d-none d-sm-block d-md-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-erikablog-dropdown-menu">
        <li><%= link_to "Our work", our_work_path, class: "navbar-wagon-item navbar-lab-link" %></li>
        <!--<li><%= link_to "Success stories", success_stories_path, class: "navbar-wagon-item navbar-lab-link" %></li>-->
        <li><%= link_to "Services", services_path, class: "navbar-wagon-item navbar-lab-link" %></li>
        <li><%= link_to "Prices", prices_path, class: "navbar-wagon-item navbar-lab-link" %></li>
        <li><%= link_to "Events", events_path, class: "navbar-wagon-item navbar-lab-link" %></li>
        <li><a class="navbar-wagon-item navbar-lab-link" href="https://blog.elbornlab.com">Blog</a></li>
        <li><%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-lab-link" %></li> 
      </ul>
    </div>
  </div>
</div>

</div>